baseURL = "https://fiverr-soundtown.netlify.app"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "SoundTown"
summaryLength = 10
RelativeURLs = false
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 8
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true

[params]
  author = "John Doe"
  site_name = "SoundTown"
  description = "SoundTown is an online music collaboration platform, focused on iterating on small ideas into big ideas. The main functionality at the moment is communication across groups/teams of people, uploading audio files and commenting on them."
  locale = "en-US"
  type = "website"


