baseURL = "https://sound.town"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "SoundTown"
summaryLength = 10
RelativeURLs = true
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 8
enableGitInfo = true
pygmentsCodefences = true
pygmentsUseClasses = true

[params]
  author = "Michael Kochell"
  site_name = "SoundTown"
  description = "SoundTown is an online music collaboration platform, focused on iterating on small ideas into big ideas. Create a workspace for your band, community, or to manage your clients. Communicate across groups/teams of people, upload project files, and comment/trim audio files to share ideas."
  locale = "en-US"
  type = "website"

  primary_color = "#30B561" # Green Color

  landing_title = "Online Music Collaboration Platform"
  landing_description = "Streamline your music creation process"
  background_image = "/assets/images/bg.webp"

  learn_more_url = "#"
  try_now_url = "https://soundtown.app"
  log_in_url = "https://soundtown.app/login"

  app_image_on_desktop = "/assets/images/app.webp"
  app_image_on_mobile = "/assets/images/app-mobile.webp"

  about = "SoundTown is an online music collaboration platform, focused on iterating on small ideas into big ideas. Create a workspace for your band, community, or to manage your clients. Communicate across groups/teams of people, upload project files, and comment/trim audio files to share ideas."

  testimonials = [
    # [
      # 'Photo Url',
      # 'Name',
      # 'Testimonial'
    # ],
    [
      'https://assets.sound.town/jimmy.jpg',
      'Jimmy Miller',
      "I love how all the text that I write on my posts is queryable. I can search and find my tags so easily. It's fun to collaborate on music creations with my friends."
    ],
    [
      '/assets/images/m1.webp',
      'Abanz Levana',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus. Eget molestie donec et molestie ut a maecenas. Purus pharetra dictumst purus consequat sed orci facilisi.'
    ],
    [
      '/assets/images/m3.webp',
      'Xie Tzuyu',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus.'
    ],
    [
      '/assets/images/m3.webp',
      'Xie Tzuyu',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diam dictum magna sociis arcu etiam cursus.'
    ]
  ]

  contact_us_url = "#"
  privacy_url = "#"
  terms_url = "#"
  help_url = "#"


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "development"
URL = "s3://dev.sound.town?region=us-east-1"

[[deployment.targets]]
name = "production"
URL = "s3://sound.town?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>

[[deployment.matchers]]
# Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
# Set custom content type for /sitemap.xml
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "no-cache no-store must-revalidate"
gzip = true
