name: Hugo S3

on:
  pull_request:
    branches: [ main ]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Build and deploy
        uses: AlbertMorenoDEV/deploy-hugo-to-s3-action@v0.0.3
        with:
          hugo-version: 0.89.0
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
