name: Hugo S3

on:
  pull_request:
    branches: [ main ]

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
          
      - name: Deploy site
        uses: plopcas/hugo-s3-action@v1.3.0
        env:
          AWS_REGION: 'eu-west-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MINIFY: 'false'
